FORMAT: 1A
HOST: https://api.hoist.io

# Hoist HTTP API

# Event API root [/events]


## Retrieve Event Stream [GET]
+ Response 200 (application/json)
 + Body
    [{
  "eventId":"{eventid}",
  "eventName":"{eventName}"
}]
