window.esdocSearchIndex = [
  [
    "api.hoi.io/lib/api_controllers/bucket_controller.js~bucketcontroller",
    "class/lib/api_controllers/bucket_controller.js~BucketController.html",
    "<span>BucketController</span> <span class=\"search-result-import-path\">api.hoi.io/lib/api_controllers/bucket_controller.js</span>",
    "class"
  ],
  [
    "api.hoi.io/lib/api_controllers/event_controller.js~eventcontroller",
    "class/lib/api_controllers/event_controller.js~EventController.html",
    "<span>EventController</span> <span class=\"search-result-import-path\">api.hoi.io/lib/api_controllers/event_controller.js</span>",
    "class"
  ],
  [
    "api.hoi.io/lib/api_controllers/health_check_controller.js~eventcontroller",
    "class/lib/api_controllers/health_check_controller.js~EventController.html",
    "<span>EventController</span> <span class=\"search-result-import-path\">api.hoi.io/lib/api_controllers/health_check_controller.js</span>",
    "class"
  ],
  [
    "api.hoi.io/lib/authentication/hoist_plugin.js~hoistauthentication",
    "class/lib/authentication/hoist_plugin.js~HoistAuthentication.html",
    "<span>HoistAuthentication</span> <span class=\"search-result-import-path\">api.hoi.io/lib/authentication/hoist_plugin.js</span>",
    "class"
  ],
  [
    "api.hoi.io/lib/router.js~router",
    "class/lib/router.js~Router.html",
    "<span>Router</span> <span class=\"search-result-import-path\">api.hoi.io/lib/router.js</span>",
    "class"
  ],
  [
    "api.hoi.io/lib/server.js~server",
    "class/lib/server.js~Server.html",
    "<span>Server</span> <span class=\"search-result-import-path\">api.hoi.io/lib/server.js</span>",
    "class"
  ],
  [
    "api.hoi.io/lib/api_controllers/bucket_controller.js~bucketcontroller",
    "variable/index.html#static-variable-bucketController",
    "<span>bucketController</span> <span class=\"search-result-import-path\">api.hoi.io/lib/api_controllers/bucket_controller.js</span>",
    "variable"
  ],
  [
    "api.hoi.io/lib/api_controllers/event_controller.js~eventcontroller",
    "variable/index.html#static-variable-eventController",
    "<span>eventController</span> <span class=\"search-result-import-path\">api.hoi.io/lib/api_controllers/event_controller.js</span>",
    "variable"
  ],
  [
    "api.hoi.io/lib/api_controllers/health_check_controller.js~eventcontroller",
    "variable/index.html#static-variable-eventController",
    "<span>eventController</span> <span class=\"search-result-import-path\">api.hoi.io/lib/api_controllers/health_check_controller.js</span>",
    "variable"
  ],
  [
    "api.hoi.io/lib/authentication/hoist_plugin.js~hoistauthentication",
    "variable/index.html#static-variable-hoistAuthentication",
    "<span>hoistAuthentication</span> <span class=\"search-result-import-path\">api.hoi.io/lib/authentication/hoist_plugin.js</span>",
    "variable"
  ],
  [
    "api.hoi.io/lib/authentication/hoist_plugin.js~register",
    "function/index.html#static-function-register",
    "<span>register</span> <span class=\"search-result-import-path\">api.hoi.io/lib/authentication/hoist_plugin.js</span>",
    "function"
  ],
  [
    "api.hoi.io/lib/router.js~router",
    "variable/index.html#static-variable-router",
    "<span>router</span> <span class=\"search-result-import-path\">api.hoi.io/lib/router.js</span>",
    "variable"
  ],
  [
    "api.hoi.io/lib/server.js~server",
    "variable/index.html#static-variable-server",
    "<span>server</span> <span class=\"search-result-import-path\">api.hoi.io/lib/server.js</span>",
    "variable"
  ],
  [
    "bucketcontroller lib/api_controllers/bucket_controller.js~bucketcontroller,bucketcontroller",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html#lineNumber23",
    "Bucket Routes",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html#lineNumber77",
    "Bucket Routes GET /bucket/{key}",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html#lineNumber159",
    "Bucket Routes GET /bucket/{key} with hoist err while getting bucket",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html#lineNumber177",
    "Bucket Routes GET /bucket/{key} with hoist err while getting bucket responds with 500",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html#lineNumber78",
    "Bucket Routes GET /bucket/{key} with matching bucket",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html#lineNumber111",
    "Bucket Routes GET /bucket/{key} with matching bucket returns 200",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html#lineNumber101",
    "Bucket Routes GET /bucket/{key} with matching bucket returns the bucket JSON",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html#lineNumber104",
    "Bucket Routes GET /bucket/{key} with matching bucket sends correct context to pipeline",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html#lineNumber137",
    "Bucket Routes GET /bucket/{key} with no bucket key supplied",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html#lineNumber155",
    "Bucket Routes GET /bucket/{key} with no bucket key supplied responds with 404 NOT FOUND",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html#lineNumber115",
    "Bucket Routes GET /bucket/{key} with no matching bucket",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html#lineNumber133",
    "Bucket Routes GET /bucket/{key} with no matching bucket responds with 404 NOT FOUND",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html#lineNumber181",
    "Bucket Routes GET /bucket/{key} with non hoist err while getting bucket",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html#lineNumber199",
    "Bucket Routes GET /bucket/{key} with non hoist err while getting bucket responds with 500",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html#lineNumber56",
    "Bucket Routes Sets up correct routes",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html#lineNumber65",
    "Bucket Routes Sets up correct routes creates GET /bucket/{key}",
    "test"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/stream_tests.js.html#lineNumber18",
    "GET /events",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/stream_tests.js.html#lineNumber128",
    "GET /events on call with a token",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/stream_tests.js.html#lineNumber213",
    "GET /events on call with a token polls for any messages in the queue",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/stream_tests.js.html#lineNumber219",
    "GET /events on call with a token removes messages from the queue",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/stream_tests.js.html#lineNumber216",
    "GET /events on call with a token returns the token",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/stream_tests.js.html#lineNumber229",
    "GET /events on call with expired token",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/stream_tests.js.html#lineNumber281",
    "GET /events on call with expired token returns a token",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/stream_tests.js.html#lineNumber272",
    "GET /events on call with expired token sets up a new queue",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/stream_tests.js.html#lineNumber51",
    "GET /events on initial call",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/stream_tests.js.html#lineNumber113",
    "GET /events on initial call links the queue to the correct event exchange",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/stream_tests.js.html#lineNumber102",
    "GET /events on initial call links the token to a rabbit queue",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/stream_tests.js.html#lineNumber99",
    "GET /events on initial call responds with 200|OK",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/stream_tests.js.html#lineNumber96",
    "GET /events on initial call returns new token code",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/stream_tests.js.html#lineNumber105",
    "GET /events on initial call saves a token to the db",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/stream_tests.js.html#lineNumber124",
    "GET /events on initial call sets expiry on the queue",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/post_event_tests.js.html#lineNumber18",
    "POST /event/{eventName}",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/post_event_tests.js.html#lineNumber51",
    "POST /event/{eventName} with matching eventName",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/post_event_tests.js.html#lineNumber82",
    "POST /event/{eventName} with matching eventName raises the event",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/post_event_tests.js.html#lineNumber92",
    "POST /event/{eventName} with matching eventName responds with 201 CREATED",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/post_event_tests.js.html#lineNumber88",
    "POST /event/{eventName} with matching eventName returns the event",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/post_event_tests.js.html#lineNumber96",
    "POST /event/{eventName} with pipeline.raise failing",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/api_controller_tests/event_api/post_event_tests.js.html#lineNumber120",
    "POST /event/{eventName} with pipeline.raise failing responds with a 500",
    "test"
  ],
  [
    "lib/api_controllers/bucket_controller.js",
    "file/lib/api_controllers/bucket_controller.js.html",
    "lib/api_controllers/bucket_controller.js",
    "file"
  ],
  [
    "lib/api_controllers/bucket_controller.js~bucketcontroller#constructor",
    "class/lib/api_controllers/bucket_controller.js~BucketController.html#instance-constructor-constructor",
    "lib/api_controllers/bucket_controller.js~BucketController#constructor",
    "method"
  ],
  [
    "lib/api_controllers/bucket_controller.js~bucketcontroller#getbucket",
    "class/lib/api_controllers/bucket_controller.js~BucketController.html#instance-method-getBucket",
    "lib/api_controllers/bucket_controller.js~BucketController#getBucket",
    "method"
  ],
  [
    "lib/api_controllers/bucket_controller.js~bucketcontroller#maproutes",
    "class/lib/api_controllers/bucket_controller.js~BucketController.html#instance-method-mapRoutes",
    "lib/api_controllers/bucket_controller.js~BucketController#mapRoutes",
    "method"
  ],
  [
    "lib/api_controllers/event_controller.js",
    "file/lib/api_controllers/event_controller.js.html",
    "lib/api_controllers/event_controller.js",
    "file"
  ],
  [
    "lib/api_controllers/event_controller.js~eventcontroller#constructor",
    "class/lib/api_controllers/event_controller.js~EventController.html#instance-constructor-constructor",
    "lib/api_controllers/event_controller.js~EventController#constructor",
    "method"
  ],
  [
    "lib/api_controllers/event_controller.js~eventcontroller#createevent",
    "class/lib/api_controllers/event_controller.js~EventController.html#instance-method-createEvent",
    "lib/api_controllers/event_controller.js~EventController#createEvent",
    "method"
  ],
  [
    "lib/api_controllers/event_controller.js~eventcontroller#getevent",
    "class/lib/api_controllers/event_controller.js~EventController.html#instance-method-getEvent",
    "lib/api_controllers/event_controller.js~EventController#getEvent",
    "method"
  ],
  [
    "lib/api_controllers/event_controller.js~eventcontroller#geteventpayload",
    "class/lib/api_controllers/event_controller.js~EventController.html#instance-method-getEventPayload",
    "lib/api_controllers/event_controller.js~EventController#getEventPayload",
    "method"
  ],
  [
    "lib/api_controllers/event_controller.js~eventcontroller#getstream",
    "class/lib/api_controllers/event_controller.js~EventController.html#instance-method-getStream",
    "lib/api_controllers/event_controller.js~EventController#getStream",
    "method"
  ],
  [
    "lib/api_controllers/event_controller.js~eventcontroller#maproutes",
    "class/lib/api_controllers/event_controller.js~EventController.html#instance-method-mapRoutes",
    "lib/api_controllers/event_controller.js~EventController#mapRoutes",
    "method"
  ],
  [
    "lib/api_controllers/health_check_controller.js",
    "file/lib/api_controllers/health_check_controller.js.html",
    "lib/api_controllers/health_check_controller.js",
    "file"
  ],
  [
    "lib/api_controllers/health_check_controller.js~eventcontroller#constructor",
    "class/lib/api_controllers/health_check_controller.js~EventController.html#instance-constructor-constructor",
    "lib/api_controllers/health_check_controller.js~EventController#constructor",
    "method"
  ],
  [
    "lib/api_controllers/health_check_controller.js~eventcontroller#heartbeat",
    "class/lib/api_controllers/health_check_controller.js~EventController.html#instance-method-heartbeat",
    "lib/api_controllers/health_check_controller.js~EventController#heartbeat",
    "method"
  ],
  [
    "lib/api_controllers/health_check_controller.js~eventcontroller#maproutes",
    "class/lib/api_controllers/health_check_controller.js~EventController.html#instance-method-mapRoutes",
    "lib/api_controllers/health_check_controller.js~EventController#mapRoutes",
    "method"
  ],
  [
    "lib/authentication/hoist_plugin.js",
    "file/lib/authentication/hoist_plugin.js.html",
    "lib/authentication/hoist_plugin.js",
    "file"
  ],
  [
    "lib/authentication/hoist_plugin.js~hoistauthentication#authenticate",
    "class/lib/authentication/hoist_plugin.js~HoistAuthentication.html#instance-method-authenticate",
    "lib/authentication/hoist_plugin.js~HoistAuthentication#authenticate",
    "method"
  ],
  [
    "lib/authentication/hoist_plugin.js~hoistauthentication#constructor",
    "class/lib/authentication/hoist_plugin.js~HoistAuthentication.html#instance-constructor-constructor",
    "lib/authentication/hoist_plugin.js~HoistAuthentication#constructor",
    "method"
  ],
  [
    "lib/authentication/hoist_plugin.js~hoistauthentication#scheme",
    "class/lib/authentication/hoist_plugin.js~HoistAuthentication.html#instance-method-scheme",
    "lib/authentication/hoist_plugin.js~HoistAuthentication#scheme",
    "method"
  ],
  [
    "lib/router.js",
    "file/lib/router.js.html",
    "lib/router.js",
    "file"
  ],
  [
    "lib/router.js~router#map",
    "class/lib/router.js~Router.html#instance-method-map",
    "lib/router.js~Router#map",
    "method"
  ],
  [
    "lib/server.js",
    "file/lib/server.js.html",
    "lib/server.js",
    "file"
  ],
  [
    "lib/server.js~hapiserver",
    "external/index.html",
    "lib/server.js~HapiServer",
    "external"
  ],
  [
    "lib/server.js~reply",
    "external/index.html",
    "lib/server.js~Reply",
    "external"
  ],
  [
    "lib/server.js~request",
    "external/index.html",
    "lib/server.js~Request",
    "external"
  ],
  [
    "lib/server.js~server#constructor",
    "class/lib/server.js~Server.html#instance-constructor-constructor",
    "lib/server.js~Server#constructor",
    "method"
  ],
  [
    "lib/server.js~server#start",
    "class/lib/server.js~Server.html#instance-method-start",
    "lib/server.js~Server#start",
    "method"
  ],
  [
    "lib/server.js~server#stop",
    "class/lib/server.js~Server.html#instance-method-stop",
    "lib/server.js~Server#stop",
    "method"
  ],
  [
    "tests/unit_tests/api_controller_tests/bucket_controller_tests.js",
    "test-file/tests/unit_tests/api_controller_tests/bucket_controller_tests.js.html",
    "tests/unit_tests/api_controller_tests/bucket_controller_tests.js",
    "testFile"
  ],
  [
    "tests/unit_tests/api_controller_tests/event_api/post_event_tests.js",
    "test-file/tests/unit_tests/api_controller_tests/event_api/post_event_tests.js.html",
    "tests/unit_tests/api_controller_tests/event_api/post_event_tests.js",
    "testFile"
  ],
  [
    "tests/unit_tests/api_controller_tests/event_api/stream_tests.js",
    "test-file/tests/unit_tests/api_controller_tests/event_api/stream_tests.js.html",
    "tests/unit_tests/api_controller_tests/event_api/stream_tests.js",
    "testFile"
  ],
  [
    "tests/unit_tests/api_controller_tests/event_controller_tests.js",
    "test-file/tests/unit_tests/api_controller_tests/event_controller_tests.js.html",
    "tests/unit_tests/api_controller_tests/event_controller_tests.js",
    "testFile"
  ],
  [
    "tests/unit_tests/server_tests.js",
    "test-file/tests/unit_tests/server_tests.js.html",
    "tests/unit_tests/server_tests.js",
    "testFile"
  ]
]